#ifndef CONFIGURATION_HPP
#define CONFIGURATION_HPP

#define TRIGGER_PIN 18
#define ECHO_PIN 17
#define SENSOR_TRIGGER_TIME 10

#define MOTOR_STEP_PIN 15
#define MOTOR_DIR_PIN 14
#define STEP_ANGLE 1.80f

enum MOTOR_DIRECTION { COUNTER_CLOCKWISE = 1, CLOCKWISE = 0 };



#endif // CONFIGURATION_HPP
